# TODO Make a secret for the mssql_sa_password
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "dev-sql-data.fullname" . }}
  labels:
    app: {{ template "dev-sql-data.name" . }}
    chart: {{ template "dev-sql-data.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "dev-sql-data.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "dev-sql-data.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ACCEPT_EULA
            value: "{{ .Values.ACCEPT_EULA.value | upper }}"
          - name: MSSQL_AGENT_ENABLED
            value: "{{ .Values.MSSQL_AGENT_ENABLED.value | upper }}"
          - name: MSSQL_PID
            value: {{ .Values.inf.sql.common.pid }}
          - name: SA_PASSWORD
            value: {{ .Values.inf.sql.common.pwd }}
          volumeMounts:
            - name: mssql
              mountPath: "/var/opt/mssql"
            - name: mssql-config-volume
              mountPath: /var/opt/config
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: TCP
      volumes:
      - name: mssql-config-volume
        configMap:
          name: mssql
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi ##Change to 8 in prod
