# Service qui permet aux autres pods d'accéder à la base de données SQL Server
# via l'url dev-sql-data.default.svc.cluster.local:1433
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sql-name" . }}
  labels:
    # les valeurs viennent du template _helpers.tpl
    app: {{ template "dev-sql-data.name" . }}
    chart: {{ template "dev-sql-data.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "dev-sql-data.name" . }}
    release: {{ .Release.Name }}

---
## Service qui permet d'exposer le pod SQL Server à l'extérieur du cluster Kubernetes
## via une IP publique et le port 1433 (pour le dev en local on est sur localhost:1433)
apiVersion: v1
kind: Service
metadata:
  name: dev-sql-data-0
spec:
  type: LoadBalancer
#   externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: dev-sql-data-0
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  loadBalancerSourceRanges:
  # IP Adress that you want to allow access to your SQL Server
